spring:
  application:
    name: push-server

zookeeper:
  connect-string: 192.168.29.131:2181, 192.168.29.132:2181, 192.168.29.133:2181
  namespace: PigeonPush
  connection-timeout-ms: 150000
  session-timeout-ms: 600000
  base-sleep-time-ms: 30000
  max-retries: 5

push-server:
  port: 8793
  ioThreads: 16

dubbo:
  registry:
    address: 192.168.29.131:2181, 192.168.29.132:2181, 192.168.29.133:2181
    protocol: zookeeper
  scan:
    base-packages: com.liewmanchoi.service.impl
  protocol:
    name: dubbo
    port: 12345
  application:
    name: PushServer-provider