spring:
  kafka:
    consumer:
      bootstrap-servers: 192.168.29.131:9092, 192.168.29.134:9092, 192.168.29.135:9092


dubbo:
  registry:
    address: 192.168.29.131:2181, 192.168.29.132:2181, 192.168.29.133:2181
    protocol: zookeeper
  scan:
    base-packages: com.liewmanchoi.service.impl
  protocol:
    name: dubbo
    port: 21131
  application:
    name: PushServer-delivery
    id: PushServer-delivery
  consumer:
    check: false
logging:
  file: delivery.log
  register-shutdown-hook: true
  path: /var/log/PushPigeon